medata:
    tls:
        ca: ./build/package/proxy/cert/ca.pem
        cert: ./build/package/proxy/cert/proxy.pem
        key: ./build/package/proxy/cert/proxy-key.pem
    grace_time_out: 15s
    scheme: https
    host: :8120
    system_log:
        path: ./log/sys.log
        level: DEBUG
server:
    tls:
        ca: ./build/package/proxy/cert/ca.pem
        cert: ./build/package/proxy/cert/server.pem
        key: ./build/package/proxy/cert/server-key.pem
    grace_time_out: 5s
    scheme: https
    host: :8121
    request_log:
        path: ./log/proxy.log
        level: INFO
