server:
    medata:
        - server_name: proxy
          scheme: http
          port: 8120
          grace_time_out: 15s
          mode: Random
          path: /obs/
          location_list:
            - proxy_pass: http://127.0.0.1:8150/v1/
              weight: 1
