medata:
    host: :8120
middleware:
    balance_node:
        obs:
            scheme: http
            host: ""
            weight: 1.1
    rate_limit:
        every: 10s
        burst: 2000
        mode: 0
