server:
    medata:
        - name: server1
          scheme: http
          port: 8120
          grace_time_out: 10s
        - name: server2
          scheme: https
          port: 8121
          tls:
            cert: ./conf/cert.pem
            key: ./conf/key.pem
          grace_time_out: 10s
middleware:
    replaceHost:
        scheme: http
        host: 127.0.0.1:8150
