definitions:
  e.Response:
    properties:
      code:
        type: string
      extra:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a server API.
  title: PROXY Swagger API
  version: "1.0"
paths:
  /v1/handlers:
    post:
      consumes:
      - application/json
      description: 更新中间件
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.Response'
      security:
      - ApiKeyAuth: []
      summary: Handlers
      tags:
      - Handler
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Auth-Token
    type: apiKey
swagger: "2.0"
