definitions:
  dynamic.BalanceNode:
    properties:
      add:
        type: boolean
      host:
        type: string
      metadata:
        additionalProperties:
          type: string
        type: object
      scheme:
        type: string
      weight:
        type: number
    required:
    - host
    type: object
  dynamic.RateLimit:
    properties:
      burst:
        type: integer
      every:
        type: string
    type: object
  dynamic.Switch:
    properties:
      add:
        type: boolean
      node:
        $ref: '#/definitions/dynamic.BalanceNode'
        type: object
      service_name:
        type: string
    required:
    - node
    - service_name
    type: object
  response.Response:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a obs server.
  license: {}
  title: obs Swagger API
  version: "1.0"
paths:
  /api/v1/mid/limit:
    post:
      consumes:
      - application/json
      description: update rate limit middleware config
      parameters:
      - description: rate limit config
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dynamic.RateLimit'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: update rate limit
      tags:
      - middleware
  /api/v1/mid/switch:
    post:
      consumes:
      - application/json
      description: update switch middleware config
      parameters:
      - description: switch config
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dynamic.Switch'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: update switch
      tags:
      - middleware
  /debug/pprof/heap:
    get:
      consumes:
      - application/json
      description: get pprof heap
      produces:
      - application/octet-stream
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: pprof heap
      tags:
      - pprof
  /debug/pprof/index:
    get:
      consumes:
      - application/json
      description: get pprof profile
      parameters:
      - default: "30"
        description: second default(30)
        in: query
        name: seconds
        type: string
      produces:
      - application/octet-stream
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: pprof profile
      tags:
      - pprof
  /debug/pprof/profile:
    get:
      consumes:
      - application/json
      description: get pprof profile
      parameters:
      - default: "30"
        description: second default(30)
        in: query
        name: seconds
        type: string
      produces:
      - application/octet-stream
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: pprof profile
      tags:
      - pprof
  /debug/pprof/trace:
    get:
      consumes:
      - application/json
      description: get pprof trace
      parameters:
      - default: "30"
        description: second default(30)
        in: query
        name: seconds
        type: string
      produces:
      - application/octet-stream
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: pprof trace
      tags:
      - pprof
swagger: "2.0"
