[package]
name = "web"
version = "0.1.0"
authors = ["crochee <2843065113@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18.0"